---
collections:
  - name: kubernetes.core
    version: '>=2.3.2'
  - name: operator_sdk.util
    version: "0.4.0"
  - name: community.windows
    version: "1.12.0"
  - name: ansible.windows
    version: "1.13.0"
  - name: community.general
    version: "6.3.0"
